name: Update Contribution Activity

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate Activity SVG
        uses: cicirello/user-statistician@v1
        with:
          image-file: profile/userstats.svg
          custom-title: "GitHub Activity"
          colors: dark
          border-radius: 8
          show-border: true
          max-languages: 8
          fail-on-error: true
          commit-and-push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
